version: "3.7"

services:
  junior:
    image: stevenxie/junior:latest
    build:
      context: .
      cache_from:
        - stevenxie/junior:latest
        - busybox:1.29
        - stevenxie/junior:builder
        - golang:1.10-alpine
    container_name: junior
    ports:
      - "3000:80"
